# file: Makefile
# author: 2020114658_LEE Yoon Seo
# datetime: 2021-12-02 13:21
# description: Makefile for read, pipe2, pipe3

all : read pipe2 pipe3

read : read.o
	gcc read.c -o read

pipe2 : pipe2.o
	gcc pipe2.c -o pipe2

pipe3 : pipe3.o
	gcc pipe3.c -o pipe3
