# file: Makefile
# author: 2020114658_LEE Yoon Seo
# datetime: 2021-11-11 19:42
# description: Makefile of waitdemo2, waitdemo3



all: waitdemo2 waitdemo3

waitdemo2: waitdemo2.o
	gcc waitdemo2.c -o waitdemo2

waitdemo3: waitdemo3.o
	gcc waitdemo3.c -o waitdemo3