# file name: Makefile
# author: 2020114658_LEE Yoon Seo
# datetime: 2021-11-18 20:23
# description: makefile for smsh4

all: smsh4

smsh4: smsh4.c splitline.c execute2.c process2.c controlflow.c builtin.c varlib.c
	gcc -o smsh4 smsh4.c splitline.c execute2.c process2.c controlflow.c builtin.c varlib.c